#sudo: required

language: python

python:
  - "2.7"
#  - "3.6"

dist: trusty

services:
  - docker

before_install:
 - pip install codecov
 - pip install pytest-cov

# - docker pull smth

install:
 - pip install .
 - pip install -r requirements.txt

script:
 - py.test --cov=./
 #docker run smth run


after_success:
  - codecov

