language: python
python:
- '2.7'
dist: trusty
services:
- docker
before_install:
- pip install codecov
- pip install pytest-cov
- pip install codacy-coverage
install:
- pip install .
- pip install -r requirements.txt
script:
- py.test --cov=./
after_success:
- codecov
- coverage xml
- python-codacy-coverage -r coverage.xml
env:
  global:
    secure: umj1slijdz9HUgYLLWKzepaL4FbqvNncZt8FhUDUPchCLhLxX8hOmCU2hZbCr2HsoMayWVPfAUCH6fz9umWK5wot5+1lAHEfXTDR3bdm/jVA7CsL2igOlbqT6uRm0qKKyKCSqmz/BwEYuK7EyvWGXfbH7ePbnXhY6mnCStheKpecKEWAZOgtkWTXtLphc6fJg8lSYmz/FE1ILhALcEedZOF2UnS5Q5caiIyqsk0wE2uG8s4DWGMZqVlcgzNzMx7Db5161mZcd5mpx/8aU48/PbZkjuCQuptyIQ5xLiPm8wv6i49jYfMZqvY7a7N+FSXuRsBUbZQwJpwR+KQ2V6s2UhbzGJXjzJmQ84IU9/q5iZ2vEIN23zbRlQfqljffafxkTL3zyWta7JHAZhENxN8tpyts9gKuXUy5aZH1OEAHK3Oy0BSMKYin8MY6nWprzL99ZpnDJd0Fu9voq2pBFbiA8s7ocYuzEZtrLo93RuAODgGyV0Tw/1XTmWGE9mLvZhRokd4H+UWHrDnR44EJ2cwU6k6ObnbcMcbm9Txom5BGZG7WYRMCgm9q0uhvcfkS8YGb35ZZK3r921S3ydcEe4NrbbeNXXvJh73f1FXFbB4Xg5wcHaFQwI49QPOsCBYK+eZ1RFPnAbnJ0MlFtanPVFm/+JIyXJehURIUYJma5lDFQr8=
