#sudo: required

language: python

python:
  - "2.7"
  - "3.6"

dist: trusty

services:
  - docker

before_install:
 - pip install codecov
# - docker pull smth

install:
 - pip install .
 - pip install -r requirements.txt

script:
 - pytest
 #docker run smth run