language: python
python:
- '2.7'
dist: trusty
services:
- docker
before_install:
- pip install codecov
- pip install pytest-cov
- pip install codacy-coverage
install:
- pip install .
- pip install -r requirements.txt
script:
- py.test --cov=./
after_success:
- codecov
- coverage xml
- python-codacy-coverage -r coverage.xml
env:
  global:
    secure: r79aXLFv36Ti8/EjgKH1A2VejRK9vviIjwLaa+wWOt/zJaOmk8ek13NwqE9rmPZiDmYPPenOr0sjxtqFDEA6uEn9cLQ1g1YZdOxM6skU5RmgE0fTblirnA0wrfgeU7dWmUddSQCQ+I7IKdGvo+B0gRv3KIzGiUql9YB5Y1rbDe7vY/3kBC4IIkm0xhK8JJKv84jmiBzpS4avf2QFzECA+F7wPwdbacK15ET8MRkEXdLApqCfzqmpdyOe9W9YNDuSAQARMs463RsVJCGBbDzYNOD2IYNcf/0SY13qZciy0uX5IpHf+iLxYgcADAdTIZMv+coiy9xAY+Z5UiAEPPPPA86cwuXbvfWf+lN9PsHsdpnx132Ipb1XIoRx1SkK8N7YDl/LbNJCne28i+hfN0ovC7kQzBc654K6mOXbA1JW3nvjVytFmt7Wuk0Pf8fCz0hUOudxxyptvdDcP7K4ZZxJev/p+Wp+V8iYgDUZvmkCAYE5SXhJdG9j5Eye+MNW+wvvg1y4Ex3/bvA10P+48loGL84QwBrZF3sld/TA/Tw4KErmiXG3mXlfNq69j9Rxrr6vEOINc7d9+Uiq5AYnmMq5d3nW4QAoocHaRf/0u0T6nsmrk8oH8wvytqTBANdsrSa0r/1mYEOOXgkasWJRqOHjSzB2hm2aJNxIVNP6Mbi9bBk=
